apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluentbit
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters, and output
  # =======================================================
  fluent-bit.conf: |
    [SERVICE]
      Flush         5
      Log_Level     debug
      Daemon        off
      Parsers_File  parsers.conf
      HTTP_Server   On
      HTTP_Listen   0.0.0.0
      HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-kafka.conf

  input-kubernetes.conf: |
    [INPUT]
      Name            tail
      Path            /var/log/containers/*test*.log
      Key             message
      Parser          default
      Path_Key        file
      Tag             kube.*
      Mem_Buf_Limit   5MB
      Skip_Long_Lines On
      Read_from_head  true

  filter-kubernetes.conf: |
    [FILTER]
      Name                kubernetes
      Match               kube.*
      Kube_URL            https://kubernetes.default.svc:443
      Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
      Merge_Log           On
      K8S-Logging.Parser  On
      K8S-Logging.Exclude On
      Merge_Log_Key       application_log

    [FILTER]
      Name        lua
      Match       kube.*
      script      map_app_tenant.lua
      call        map_app_tenant

    [FILTER]
      Name modify
      Match kube.*
      Remove kubernetes.docker_id
      Remove kubernetes.host 
      Remove kubernetes.labels.app
      Remove kubernetes.container_hash
      Remove kubernetes.pod_id
      Remove kubernetes.labels.version
      Remove kubernetes.container_image
      Remove kubernetes.labels.version

  map_app_tenant.lua: |
    function map_app_tenant(tag, timestamp, record)
        record["app_id"] = record["kubernetes"]["container_name"]
        record["tenant_id"] = record["kubernetes"]["namespace_name"]
        return 1, timestamp, record
    end

  output-kafka.conf: |
    [OUTPUT]
      Name                  s3
      Match                 kube.*
      bucket                bhargav-zipfiles
      region                blr1
      s3_key_format         /zipfiles/$TAG[4]/%Y%m%d/$UUID.gz
      total_file_size       5M
      upload_timeout        1m
      use_put_object        On
      compression           gzip
      static_file_path      On
      endpoint              blr1.digitaloceanspaces.com
      json_date_key         timestamp

  parsers.conf: |
    [PARSER]
      Name        default
      Format      regex
      Regex       ^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) - (?<message>.*)$
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S
      Time_Keep   On
    