apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit3
  namespace: fluentbit
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:3.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "DO00Z9HEJHJGT3744X47"
        - name: AWS_SECRET_ACCESS_KEY
          value: "Fd9TE2/ePjcNNWKv6h7ayfu0Zaw56h10chogPhgtutQ"
        - name: AWS_ENDPOINT_URL
          value: "blr1.digitaloceanspaces.com"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-etc
          mountPath: /fluent-bit/etc/
        - name: mnt
          mountPath: /mnt
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-etc
        configMap:
          name: fluent-bit-config
      - name: mnt
        hostPath:
          path: /mnt
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
